### ISSUE TITLE
ability to disable hardware player

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/groovebasin#129]
the user should be able to run groovebasin using only the encoder.

**Comment by diogocp** [comment]
I'm running into this problem. Runs fine with SDL_AUDIODRIVER=dummy, but segfaults without it. Shouldn't there be a config.json option to disable it?

    unable to execute xdg-user-dir: spawn xdg-user-dir ENOENT
    unable to init SDL audio subsystem: No available audio device
    sh: line 1: 24574 Segmentation fault      node lib/server.js --verbose

npm-debug.log:
````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose config Skipping project config: /var/lib/groovebasin/.npmrc. (matches userconfig)
5 verbose run-script [ 'predev', 'dev', 'postdev' ]
6 info predev groovebasin@1.5.1
7 info dev groovebasin@1.5.1
8 verbose unsafe-perm in lifecycle true
9 info groovebasin@1.5.1 Failed to exec dev script
10 verbose stack Error: groovebasin@1.5.1 dev: `npm run build && node lib/server.js --verbose`
10 verbose stack Exit status 139
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid groovebasin@1.5.1
12 verbose cwd /var/lib/groovebasin
13 error Linux 4.1.4-hardened
14 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
15 error node v0.12.6
16 error npm  v2.11.2
17 error code ELIFECYCLE
18 error groovebasin@1.5.1 dev: `npm run build && node lib/server.js --verbose`
18 error Exit status 139
19 error Failed at the groovebasin@1.5.1 dev script 'npm run build && node lib/server.js --verbose'.
19 error This is most likely a problem with the groovebasin package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     npm run build && node lib/server.js --verbose
19 error You can get their info via:
19 error     npm owner ls groovebasin
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
````

**Comment by andrewrk** [comment]
wow, a segfault. I'll look into that.

But first, I'm going to finish the work I'm doing on the [soundio branch of libgroove](https://github.com/andrewrk/libgroove/tree/soundio). This completely removes the SDL dependency and replaces it with [libsoundio](https://github.com/andrewrk/libsoundio). This will likely result in deleting the code that caused the segfault.

**Comment by diogocp** [comment]
Thanks. Anyway, it's working great with the workaround.

I have just started playing around with Groove Basin and I think I'm sold. I'm a long time Clementine user (and Amarok 1.4 before that), looking for a player with a similar interface but with the ability to sit on a server, streaming to and being controlled from my various devices. A few months ago I tried mpd, but the streaming sucked because of the huge buffers.

**Comment by andrewrk** [comment]
Cool. :) Amarok 1.4 was my favorite player back in the day. Groove Basin has some issues and isn't quite done yet feature-wise, but I use it every day for my own music player, so even when progress can be slow at times, it always marches forward. Enjoy, and bug reports are welcome.

**Comment by diogocp** [comment]
Turns out that compiling libsdl2 with ALSA support fixes the problem. Weird, since I don't even have sound support in the kernel.
