### ISSUE TITLE
In browser decoding of FLAC / AAC / ALAC files using Aurora.js

### ISSUE THREAD

**Issue by GitHubGeek** [andrewrk/groovebasin#422]
Hi, new Groove Basin user here! Is it possible to have the option to decode music files client-side, to lighten server's CPU load?

[Aurora.js](https://github.com/audiocogs/aurora.js) is a working implementation of client-side decoding.

**Comment by andrewrk** [comment]
GrooveBasin uses libav/FFmpeg to decode audio. That means that pretty much every format ever is supported. Trying to move that to the browser is impractical and trying to do a hybrid is inelegant and problematic.

**Comment by norpol** [comment]
I mean, it's a 'funny' doing the audio normalization on the client, sending the normalized data back to the server, but why should you want to do that?
