### ISSUE TITLE
Error during "npm run build" on RPi2

### ISSUE THREAD

**Issue by uytko** [andrewrk/groovebasin#426]
I've followed A. Kelley to build the application on RPi2. The build failed.
If needed I can provide more information.
Thank you

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.7.5
3 info using node@v0.10.29
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild groovebasin@1.5.0
6 info build groovebasin@1.5.0
7 verbose unsafe-perm in lifecycle true
8 info groovebasin@1.5.0 Failed to exec build script
9 verbose stack Error: groovebasin@1.5.0 build: `npm install && ./build`
9 verbose stack Exit status 133
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:98:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:98:17)
9 verbose stack     at maybeClose (child_process.js:755:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
10 verbose pkgid groovebasin@1.5.0
11 verbose cwd /home/root/gb/groovebasin
12 error Linux 3.18.7-v7+
13 error argv "node" "/usr/local/bin/npm" "run" "build"
14 error node v0.10.29
15 error npm  v2.7.5
16 error code ELIFECYCLE
17 error groovebasin@1.5.0 build: `npm install && ./build`
17 error Exit status 133
18 error Failed at the groovebasin@1.5.0 build script 'npm install && ./build'.
18 error This is most likely a problem with the groovebasin package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm install && ./build
18 error You can get their info via:
18 error     npm owner ls groovebasin
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by andrewrk** [comment]
Can you try this?

```
npm install
sh build
node lib/server.js
```

**Comment by uytko** [comment]
(In progress)
Thank you for your quick response.
I upgraded node to the latest version. Now, It seems to build.
I'll update my post.
