### ISSUE TITLE
Tags vs. Playlists

### ISSUE THREAD

**Issue by smoebody** [andrewrk/groovebasin#428]
Hi,

i would like to discuss the approach of tags rather than playlists. i think that tagging a song/artist/album might be a better way to organise music as such than a playlist. what a playlist really for is to organise the order of tracks in that they are played. 

groovebasins playlists are very basic right now, i think they will get more features over time, but i think most needs could be solved with tags.

if we could tag our tracks:
* it would be easier to filter your library and you can add more filters to that.
* by keeping the filter-approach one will have an hierarchical view to the tagged files

the downside of this approach is the extension of the database where every track has its own list of tags attached.

**Comment by andrewrk** [comment]
We're calling this feature "labels". Plans have been made and progress is underway. See #207 

@thejoshwolfe has some unfinished progress on this. :eyes:
