### ISSUE TITLE
Demo site is down (http://demo.groovebasin.com/)

### ISSUE THREAD

**Issue by woverton** [andrewrk/groovebasin#432]
Just letting you guys know that your demo site, http://demo.groovebasin.com,  is down.

![image](https://cloud.githubusercontent.com/assets/9078302/7317408/6e2806ba-ea78-11e4-9398-ec7db68ef6a8.png)

**Comment by woverton** [comment]
![image](https://cloud.githubusercontent.com/assets/9078302/7317421/89dd6dfa-ea78-11e4-9ca9-bb8f79c7e7b6.png)

**Comment by andrewrk** [comment]
thanks. fixed. I keep running out of disk space on that aws micro instance.

**Comment by rsynnest** [comment]
demo site is down again FYI
