### ISSUE TITLE
web client: ctrl-a should select all tracks

### ISSUE THREAD

**Issue by dohliam** [andrewrk/groovebasin#433]
Currently, pressing Ctrl-A in the playlist, sidebar or anywhere else in the web client results in selecting all text on the page (which usually is just the track title above the progress bar, not the actual tracks themselves).

In line with expected behaviour, it would probably be a good idea if the client captured Ctrl-A and selected all tracks in the playlist, or in the sidebar if that is where the focus happens to be.

* Use case 1: You search for an artist in the sidebar and get a whole bunch of results. You want to add them all to the playlist, so you press Ctrl-A and drag and drop as you would in a desktop application.
* Use case 2: You have a huge playlist and you want to delete everything, so you press Ctrl-A and then delete to clear.

**Comment by andrewrk** [comment]
This works as you described for me in firefox and chromium. what browser are you using?

**Comment by andrewrk** [comment]
Also, what groovebasin version? does http://demo.groovebasin.com/ exhibit correct behavior?

**Comment by dohliam** [comment]
Sorry I should have mentioned the relevant info -- it sounds like this might be fixed in 1.50?

I have this issue on firefox and chromium, running groovebasin 1.4.0-1.

**Comment by andrewrk** [comment]
Try it out on the demo site linked above. If it works then it was fixed in 1.5.

**Comment by dohliam** [comment]
Yes, the demo site works as expected. Will definitely check there before reporting any other issues. Thanks for your super fast response!

**Comment by andrewrk** [comment]
enjoy! I realize that 1.5 is not available in debian or ubuntu yet, but I do recommend that release. Lots of good stuff happened: https://github.com/andrewrk/groovebasin/blob/master/CHANGELOG.md#version-150-2015-01-09

**Comment by dohliam** [comment]
Wow, looks great -- you're right, I've been using the distro version without any problems for so long that I hadn't even thought about checking for new releases, but it looks like I've been missing out!

Thanks for all your hard work on this btw, groovebasin is the best (actually the only) way I've found to stream over ssh with basically no setup required.
