### ISSUE TITLE
groovebasin does not start - 'Error: Module did not self-register'

### ISSUE THREAD

**Issue by incredibleweirdo** [andrewrk/groovebasin#435]
Hello,
   Ubuntu 15.04, node v0.10.36, attempting to start groovebasin fails with the below output:

module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/lib/nodejs/ws/lib/Sender.js:11:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

This has begun seemingly just today. I have reinstalled groovebasin to attempt to resolve, but it had no effect on the error.

**Comment by andrewrk** [comment]
are you running groovebasin from apt-get, or from source?

**Comment by incredibleweirdo** [comment]
From apt-get. Which seems to install just fine.
I just installed from source, against my better judgement because dependencies nodejs-dev and nodejs-legacy would not install (unmet nodejs dependencies, despite that it was installed). However, compilation and installation worked just fine. 
It failed to start the first time when running 'npm start' within the groovebasin directory. 2nd time, strangely started. So then I ctr-C and copied my config.json into the directory and tried again... failed just like the first time, with what looked like permissions errors ('Unable to fs.watch: Error: watch ENOSP'). So did 'sudo npm start' and it's running just fine.

**Comment by andrewrk** [comment]
ENOSPC means there is no space left on the device.

Please do not run groove basin as root.

It looks like that self-register error happens when one of the binary modules are run against a different version of node than they were compiled for. If you're installing from source, `try rm -rf node_modules` and `npm install` again.

**Comment by incredibleweirdo** [comment]
Okay. I'm running just via npm start again, with no issues. It did output the ENOSPC errors a few times before starting the server. Free space is about 85 GB, though. 

Running from the groovebasin command still reports the self-register error, though. I believe that's still from the package install.

**Comment by skarekrow** [comment]
Are you possibly running out of inodes?

**Comment by andrewrk** [comment]
I don't think this particular issue is going to lead to a resolution of this problem. I am going to close it until more information surfaces.
