### ISSUE TITLE
client: prevent time display in the queue from being cut off

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/groovebasin#44]
* Time column disappears when window is too thin
* Time column can cut off part of 4-digit times

**Comment by melissanoelle** [comment]
What's/is there the smallness cut off for unsupported/too small?

**Comment by andrewrk** [comment]
I have no idea what you are talking about.

**Comment by melissanoelle** [comment]
I'm wondering about the minimum window width. To consider this bug/enhancement satisfied, do you want this column to show no matter how thin the window is, or do you have an idea of a reasonable cut off where it's ok for it not to show because nothing looks good at that size of smallness/thinness?

**Comment by andrewrk** [comment]
Ah I see. It should keep all the columns visible always, and just make the columns smaller and start cutting off the text as the window gets smaller. Also, as noted above, 4-digit times are getting cut off when they have plenty of space to grow.

**Comment by andrewrk** [comment]
And as always, if you have an idea that is better than status quo, then let's do that.
