### ISSUE TITLE
groovebasin protocol does not support encryption

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/groovebasin#447]
It's a cute idea to use the same MPD protocol port to support GrooveBasin protocol, but the MPD protocol has an inherent problem which is that it is cleartext. Groove Basin protocol is currently inheriting that problem from MPD protocol.

I'm thinking that perhaps the simplest thing is going to be for groove basin clients to use HTTPS and web sockets to access the groovebasin protocol. Otherwise we end up basically re-implementing SSL if we try to add encryption to the groovebasin protocol.

It's a bit more overhead to require clients to understand HTTP/HTTPS and websockets protocol in order to work, however these are common enough technologies that there should be no problem for client writers to find libraries to do this for them in whatever language they need.

So this issue calls for deleting a feature.

**Comment by fsateler** [comment]
+1 to reusing existing protocols, and +1 to not adding crypto directly but relying on transport crypto.
