### ISSUE TITLE
when i using common "npm run build" to build groovebasin,but npm said is not ok code 0

### ISSUE THREAD

**Issue by xgbxmgg** [andrewrk/groovebasin#451]
The following is the result of the output：
npm ERR! groovebasin@1.5.1 build: `npm install && ./build`
npm ERR! Exit status 133
npm ERR! 
npm ERR! Failed at the groovebasin@1.5.1 build script.
npm ERR! This is most likely a problem with the groovebasin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && ./build
npm ERR! You can get their info via:
npm ERR!     npm owner ls groovebasin
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.18.11-v7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! cwd /home/pi/groovebasin
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/groovebasin/npm-debug.log
npm ERR! not ok code 0。

my device is raspberry pi 2,and i work follow as link "http://www.geekfan.net/10419/"'s steps,
how can i fix it.

**Comment by andrewrk** [comment]
I don't see an error message here. Can you run the steps manually and paste the error? 

```
npm install
./build
node lib/server.js
```

**Comment by xgbxmgg** [comment]
After i run "npm install".i got message of this "Trace/breakpoint trap"

**Comment by andrewrk** [comment]
That doesn't make sense. That "error" should only happen while debugging when a programmer purposefully inserted a breakpoint instruction.

**Comment by norpol** [comment]
Hi! Please `cd grovebasin` and tell us what the output of `git rev-parse HEAD` is.
With `git status` and `git diff` you can see if there are files modified by you. You can also try to `git checkout 1.5.1` so you are on the latest "release" of groovebasin. If there were modifications of commited code you can type `git reset --hard` so these modifications are reverted (this is permanent).

**Comment by xgbxmgg** [comment]
sorry for later of reply，git rev-parse HEAD message is “70b2b9a6b99831b6a2b49db216cd3965e5709965",and the groovebasin's version is 1.5.1,also the git diff message is nothing.

**Comment by norpol** [comment]
Hm. Try to remove the current installed node version with `cd node-v0.10.29` and run `sudo make uninstall`. Afterwards install nodejs from a repository (which is better, since you'll get updates via apt). [Here's a guide](https://github.com/nodesource/distributions#debinstall). And try `npm install` again.

**Comment by xgbxmgg** [comment]
Thank you, as you said, I have done。it is success。

**Comment by andrewrk** [comment]
OK I don't understand what the problem was but glad it's resolved.

**Comment by norpol** [comment]
The problem was an outdated nodejs version.  
I think it's better to use a packaged nodejs version (like the one nodesource provides) instead of compiling & installing from source.
