### ISSUE TITLE
Support Clementine remote control protocol

### ISSUE THREAD

**Issue by emersion** [andrewrk/groovebasin#454]
This would allow users to remote control the player from an Android device, for instance.

See [`clementine-remote`](https://github.com/emersion/node-clementine-remote).

**Comment by mbelow** [comment]
hm. I think clementine-remote is quite similar to MPD clients like mpdroid, which are already supported.

**Comment by emersion** [comment]
I agree, but it is another standard and I already wrote some frontends for Clementine ([a web ui](https://github.com/emersion/clementine-remote-web) and [a MPRIS-based ui](https://github.com/emersion/clementine-remote-ui)) and I would be happy to see them work with groovebasin.

If adding the feature is not possible, is there a plugin system available? Or, would it be possible to choose between different available frontends?

**Comment by andrewrk** [comment]
Is there some document I can read to get a quick overview of the protocol? @emersion the examples in your repo are good but very simple. I'm looking for, what messages can the client send to the server and vice versa.

The MPD protocol is complete garbage and the GrooveBasin protocol is much better. I wonder where Clementine protocol fits on that line.

> If adding the feature is not possible, is there a plugin system available?

There is not a plugin system. If the feature was added I would maintain it along with the rest of the code. The code is organized into modules though; the mpd protocol interfaces with the player module and the groovebasin protocol interfaces with the player module. Supporting another protocol would be a matter of adding another module which also interfaces with the player module. It would either be easy and straightforward or require changing the way that GrooveBasin indexes data depending on how the protocol works.

**Comment by emersion** [comment]
There is a more complete example with my Clementine Node.js server here: https://github.com/emersion/node-clementine-server/blob/master/index.js#L26

But it may be easier for you to have a look to my PR ;-)

Here are the dev docs for Clementine Remote: https://github.com/clementine-player/Android-Remote/wiki/Developer-Documentation

A good point is that it's based on [protobuf](https://github.com/google/protobuf). You can see the `.proto` file here: https://github.com/clementine-player/Android-Remote/blob/master/app/src/main/java/de/qspool/clementineremote/backend/pb/remotecontrolmessages.proto

But the protocol has been designed for Clementine, so some features are missing now and some data format doesn't perfectly fit with groovebasin's (e.g. the songs list is downloaded once as a SQLite database). So it will require some work to make it work well (most of it is already implemented in `clementine-remote`).

**Comment by andrewrk** [comment]
Thanks, the .proto file was really helpful. It looks pretty on par with the MPD protocol. The client requests information and then the server returns it. I don't see a way to subscribe to changes, do you? This is one thing the Groove Basin protocol does better, I think. Instead of requesting information, you subscribe to it, and you are from then on notified whenever the thing you subscribed to changes.

**Comment by andrewrk** [comment]
I decided to not support the clementine protocol. I think it is not popular enough to care about, and it has similar flaws to the MPD protocol. Meanwhile, a first draft of the Groove Basin Protocol Specification is merged into master.

**Comment by emersion** [comment]
Wow, thanks a lot for your quick response and work. I understand your decision and I'll prefer to use Groove Basin protocol instead too.

On August 19, 2015 7:45:06 AM CEST, Andrew Kelley <notifications@github.com> wrote:
>I decided to not support the clementine protocol. I think it is not
>popular enough to care about, and it has similar flaws to the MPD
>protocol. Meanwhile, a first draft of the Groove Basin Protocol
>Specification is merged into master.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrewrk/groovebasin/issues/454#issuecomment-132453497

-- 
Simon Ser
http://emersion.fr

**Comment by andrewrk** [comment]
Cool, and if you run into something that is *not very well designed* in the Groove Basin protocol, please do file an issue and let's make it better :-)
