### ISSUE TITLE
Protocol spec

### ISSUE THREAD

**Issue by emersion** [andrewrk/groovebasin#460]
Since Clementine Protocol is _not very well-designed_, it would be nice to have docs about Groovebasin's protocol. A neutral spec would allow to build more servers & clients.

What's more, a separate package for the protocol (like it exists for Clementine: https://github.com/emersion/node-clementine-remote) would be very useful.

**Comment by andrewrk** [comment]
I started working on this in the protocol-spec branch:

https://github.com/andrewrk/groovebasin/blob/protocol-spec/doc/protocol.md

Still some more things to do before I'm going to merge it into master, but feedback is still welcome if you have any.

**Comment by andrewrk** [comment]
Here's a node package like you requested: https://github.com/andrewrk/gbremote
