### ISSUE TITLE
Pattern-based blacklisting of files in the music directory

### ISSUE THREAD

**Issue by diogocp** [andrewrk/groovebasin#463]
One problem I noticed related to slow initialization (#302) is that Groove Basin always re-scans my cover art on startup. I timed ffprobe on a few JPEG and PNG files, and it seems to take around 100-300 miliseconds on each one, with one large png taking as much as 1 second. With many thousands of these files in my music directory, this is a big waste of CPU time.

I think a good way of handling this would be to have a configuration option for blacklisting certain filename patterns, for example "*.jpg" or "Covers/".

**Comment by andrewrk** [comment]
Reasonable idea.

Another idea I had kicking around was to display all the files that are not playable and have the user either delete them, mark them as ignore, report a bug (this should be playable but groove basin cannot play it). The UI would let the user do this in bulk. The downside of this is that if you are often adding new music with .jpgs in it and you already know you want to ignore all .jpgs you'd have to mark them as "ignore" every time you imported a new album.

**Comment by diogocp** [comment]
Looks like some of those non-audio files actually end up being misdetected as audio and put into the library. Seems to happen a lot with EAC logs (more than 100 cases).

I have ~27k files in my music directory, and some 30% of them are non-audio. Here are the most common extensions:
````
  17058 flac
   5370 jpg
   1292 mp3
    976 png
    912 log
    808 cue
    161 txt
    135 pdf
    124 VOB
    117 JPG
````
Even scanning them once takes a long time, so filtering before scanning seems like a better idea to me. I don't think anyone expects their music player to play .jpg files, even if they somehow happen to contain an audio stream.

Some files would probably slip through a blacklist, and then having a UI for fixing, deleting or ignoring them could be useful. But there's some really low-hanging fruit in a simple filter like `["*.jpg", "*.png", "*.pdf", "*.log", "*.cue", "*.txt"]`.

**Comment by andrewrk** [comment]
This seems like a good idea. Here's mine:

```
6072	.mp3
504	.m4a
398	.flac
368	.mp4
293	.directory
213	.wma
201	.jpg
148	.webm
97	.ogg
28	.JPG
15	.aac
13	.MP3
13	.png
9	.m3u
8	.nfo
5	.wav
4	.log
4	.ini
3	.sfv
2	.xml
2	.fla
2	.zip
2	.cue
1	.m3u8
1	.url
1	.m
1	.txt
1	.m4p
```

So, I personally want to delete all files that aren't music, which is why I've been holding off on simply ignoring non music stuff. But I think for now until Groove Basin gets a little more advanced what you suggested is a good idea.

**Comment by thejoshwolfe** [comment]
Here's my library:

```
2735	.mp3
407	.flac
257	.m4a
186	.mp4
101	.webm
46	.wma
31	.ogg
7	.aac
2	.m
2	.wav
1	.zip
```
