### ISSUE TITLE
Queue to Groove Basin API call

### ISSUE THREAD

**Issue by tedmiston** [andrewrk/groovebasin#465]
I'd like to build a "Queue to Groove Basin" browser plugin for YouTube. Is there an API call I can make?

I'm unclear on where to start looking for endpoints (or docs) to handle login and the import from YouTube url call.

Referenced from [a tweet last week](https://twitter.com/kicksopenminds/status/631586663542693889).

**Comment by andrewrk** [comment]
Make sure you're running the latest code from master. Then take a look at the protocol specification in doc/protocol.md.

The "importUrl" message will do what you want.

**Comment by andrewrk** [comment]
[gbremote](https://github.com/andrewrk/gbremote) is a simple example demonstrating how to use the Groove Basin Protocol. Here is [how to use importUrl](https://github.com/andrewrk/gbremote/blob/master/cli.js#L251).

**Comment by andrewrk** [comment]
I think this issue is resolved; feel free to re-open if you have further questions.
