### ISSUE TITLE
SSH documentation

### ISSUE THREAD

**Issue by dohliam** [andrewrk/groovebasin#470]
I noticed that there doesn't seem to be any documentation on running Groove Basin over SSH. I've been using Groove Basin exclusively over SSH for a while now (it works great) and would be happy to write a quick guide on how to get it set up. Would it be okay to add this information to the wiki?

I've also put together a [tiny bash script](https://github.com/dohliam/groovebasin-ssh) that automates the process and might be useful to people wanting to use Groove Basin regularly to stream over ssh.

**Comment by thejoshwolfe** [comment]
`ssh -L ...`. That's pretty neat. I didn't know about that.

Looking at your script, I think there are two separate issues you're trying to solve at once.

Given that I can ssh to the computer that can run Groove Basin:

1. How do I start and stop the Groove Basin server remotely?
2. How do I connect to a running Groove Basin server as a client without doing any further configuration such as port forwarding in a router?

Those are both valid concerns, but I think they should be separate concerns. The Groove Basin server is designed to operate well if it's left running forever (that's how I use my Groove Basin server.), but it's also totally reasonable for users to want the server running only when they're actually using it. If we document the two issues separately, users can decide to combine them if they want.

**Comment by andrewrk** [comment]
@dohliam feel free to update the wiki :-)

It occurs to me that a process supervisor such as systemd, upstart, sysvinit, etc might solve the problem that you're solving with a bash script. Have you considered trying to use one of those?

The process supervisor's job is to:

 * Start the groove basin server when the computer turns on.
 * Restart groove basin if it crashes.

**Comment by dohliam** [comment]
@thejoshwolfe You're absolutely right! :+1:  I can definitely address the two issues separately in the documentation.

Luckily, the first issue is easy to resolve (assuming that one already knows how to ssh into the remote machine):

1. Log into the remote machine
2. Enter the Groove Basin folder
3. Run `groovebasin`
4. Done! The server is now up and running

The tricky part (for me, anyway) was figuring out how to connect the client to the Groove Basin server over SSH once it's running. It's not difficult, of course, but also not exactly obvious. :smile:

Basically it just involves forwarding the appropriate ports (using the `-L` option as you noticed), although I also wanted to return control of the script to the local terminal (using `-t -t`) so that the browser window could be launched automatically.

Even taking into account the extra time needed to start the Groove Basin server every time, the whole process still has a great music player up and running in about the same amount of time as most local desktop applications take to load. It would be even faster if the server was already on and the script just logged in and opened the browser window!

@andrewrk That's an interesting idea -- I hadn't thought of using a process supervisor. At the time I wrote the script, I wasn't running the Groove Basin server all the time yet, so I wanted a way to start and stop the server remotely on command. It would be easier in a lot of ways to just have the Groove Basin server run on start up and leave it running as @thejoshwolfe suggests.

If we assume that the server is always running, it just becomes a matter of connecting the client remotely, which I think might still be worthwhile explaining for people not familiar with port-forwarding over SSH.

**Comment by dohliam** [comment]
Finally got some time to write this up -- here's the link:

https://github.com/andrewrk/groovebasin/wiki/Using-Groove-Basin-over-SSH

Let me know if there's anything you'd like me to add/change. Otherwise, this issue can be safely closed. :smile:

**Comment by andrewrk** [comment]
Thanks for writing this up! It looks great.
