### ISSUE TITLE
youtube functions malfunctioning

### ISSUE THREAD

**Issue by eyecreate** [andrewrk/groovebasin#477]
I have been following master recently with my groovebasin setup because, in the past, youtube downloads break and are updated with ytdl-core quickly. Fairly recently(past week or two), youtube imports have not been working correctly. I put in some log lines in places I thought should be running and everything seemed okay in that ytdl seemed to have found the best format and was passed to the downloadfrominfo function. Nothing shows up in the logs and neither the library or any indication of action in the UI. Any ideas why this is happening?

**Comment by thejoshwolfe** [comment]
I'm getting the same thing, and so are two other users i know. The most probable explanation is that youtube changed their apis, which they do quite frequently, and ytdl-core will update to accommodate them in future version. I just tried using ytdl-core 0.7.6 and it doesn't fix the problem.

**Comment by andrewrk** [comment]
ytdl-core changed their API without updating the docs. https://github.com/fent/node-ytdl-core/issues/57

**Comment by andrewrk** [comment]
I pushed a commit which should improve the situation a bit, but until the above issue is resolved, expect issues.

**Comment by andrewrk** [comment]
OK this is confirmed fixed in 6f7f572feedc280b57a. Let me know if there is a new issue discovered.
