### ISSUE TITLE
DJ mode / basic mixing

### ISSUE THREAD

**Issue by mrdomino** [andrewrk/groovebasin#483]
So the desire behind this issue is that I want to be able to talk over my stream sometimes, possibly bringing the volume down on the music while I do so, or to play [silly things like this](https://www.youtube.com/watch?v=38IFCiqc6LQ) on top of the currently playing song.

How hard would it be to build this in a non-awful way? I'm interested in pitching in time or money to make it happen.

**Comment by andrewrk** [comment]
ho boy. I can see why you'd want that but it's pretty out of scope for the project. Adding a feature like this brings in a lot of design implications.

**Comment by mrdomino** [comment]
Yeah, makes sense. Maybe some day, yadda yadda.
