### ISSUE TITLE
Something seems to be missing from the zig build instructions

### ISSUE THREAD

**Issue by BrianGallew** [andrewrk/groovebasin#524]
git branch: zig-pkg
commit: 22aa65c9bdb734369256f4d16ec050a70b1670e6
zig: 0.10.1
OS: Ubuntu 22.04.1 LTS

'''
:) geek@fred:~/src/groovebasin ; ../zig-linux-x86_64-0.10.1/zig build
/home/geek/src/groovebasin/build.zig:6:23: error: no field or member function named 'standardOptimizeOption' in 'build.Builder'
    const optimize = b.standardOptimizeOption(.{
                     ~^~~~~~~~~~~~~~~~~~~~~~~
/home/geek/src/zig-linux-x86_64-0.10.1/lib/std/build.zig:31:21: note: struct declared here
pub const Builder = struct {
                    ^~~~~~
referenced by:
    runBuild: /home/geek/src/zig-linux-x86_64-0.10.1/lib/build_runner.zig:232:22
    usage__anon_5129: /home/geek/src/zig-linux-x86_64-0.10.1/lib/build_runner.zig:242:13
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
'''
I suspect there's something missing from the git repository or build instructions.

**Comment by andrewrk** [comment]
we're using zig master branch to build the `zig-pkg` branch of groovebasin. please hold off on filing issues until we finish our work and merge it into master branch :)
