### ISSUE TITLE
zig-pkg branch : install fails with "missing top-level 'paths' field" in .zon file

### ISSUE THREAD

**Issue by samusz** [andrewrk/groovebasin#526]
I must have a _too_ new zig master master branch, as when trying to install the zig-pkg branch I get this error msg : 
```
$ zig build run
/home/samusz/repo/prog/zig/groovebasinbuild.zig.zon:1:2: error: missing top-level 'paths' field
.{
 ^
```
The weird part is the path of `build.zig.zon` is mangled in the error message and should be `/home/samusz/repo/prog/zig/groovebasin/build.zig.zon`

Zig master is the one pulled today : 
```
$ zig version
0.14.0-dev.1588+2111f4c38
```

This might be obvious, but I am clueless with zon files

**Comment by andrewrk** [comment]
my most recent work on this project is at https://codeberg.org/andrewrk/player

**Comment by samusz** [comment]
Thank you Andrew !
